### ISSUE TITLE
Dynamic menu loading

### ISSUE THREAD

**Issue by jshannon75** [jshannon75/awp_shiny_april2018#1]
We need code that loads the menu drop downs dynamically from the metadata file.

**Comment by momiji15** [comment]
I think I have solved this issue. I was able to both filter the data by category and get the data to dynamically load based on that. I sorted the descriptions so they are in ABC order as well.  I will make a commit if you think everything looks good after our meeting on Monday. Or I could just do it before.

**Comment by jshannon75** [comment]
Just go ahead and come in and push now. Good versioning is half of what
GitHub is for.

**Comment by jshannon75** [comment]
Current work flow:
Load dropdown menu with plain text choices from the metadata
Convert dropdown choice to variable code name via lookup table/metadata
Reactive: filter the atlasdata based on the selected variable
Reactive: Join the filtered data to the spatial boundaries
Map this dataset

**Comment by momiji15** [comment]
I was able to get the leaflet map working with the dynamic dropdown menu. However there are some variables with missing data or are producing an error message. Here are problem domains and variables:

- Demographics: All variables
- Health people & Environments
      *Has health insurance foreign born and naturalized
      *Has health insurance foreign born and non-citizen
      *Has health insurance native born
      *Number of Community Gardens -> error message is _'breaks' are not unique_
      *Number of  Food Pantries -> error message is _'breaks' are not unique_
      *Number of School Gardens -> error message is _'breaks' are not unique_
      *Number of Toxic Release Inventory sites -> error message is _'breaks' are not unique_
      *Percent Conservation Easement -> error message is _'breaks' are not unique_
- Housing
      *Population whose gross rent is > 30% of income
      *Total housing units
      *Total population in housing units
      *Total population in owner occupied housing
      *Total population in renter occupied housing
- Income & Employment: All variables 
- Lifelong learning
      *Bachelor's degree
      *Elementary Average Teacher Years of Experience: error message is _'breaks' are not unique_
      *High school diploma or GED
      *MA degree
      *Professional/doctorate degree
      *Some college or Associate's Degree
      *Total enrolled in nursery school & kindergarten
      *Total in grad school
      *Total in undergraduate
-Transportation: All variables

I did filter the atlasdata with the missing variables to see if I overlooked something and they weren't there. I could see if there's some way in which those variables aren't loaded if your want. As for the 'breaks' issue, I'm going to have to take a further look into that.
