### ISSUE TITLE
Variable for Total Housing Units

### ISSUE THREAD

**Issue by momiji15** [jshannon75/awp_shiny_april2018#12]
I've noticed that there is no variable for total housing units in the atlas data, however, there is a variable for total housing units in the metadata. It is listed as an option in the drop-down menu in the Demographic domain. How should I proceed with this?

**Comment by jshannon75** [comment]
Just remove that total units variable.

Let me know if you want to touch base on this next week. Have you been
keeping track on hours?

**Comment by momiji15** [comment]
There's another variable that isn't in the atlas data, but is in the metadata. This variable is "Total population in housing units"(HousPop).  As for hours, I am just tracking them in a notebook. From May 7th up to now, I've worked 11 hours and 20 minutes on the app.

We can meet next week if you want. I will be starting the internship at the library next Monday, so I will be available after 2pm from Monday to Thursday. Next Friday, I will be out of town.

**Comment by jshannon75** [comment]
Great--just keep me in the loop for now. I've got childcare until 2 the
next couple of weeks, so not as available after that.
