### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by momiji15** [jshannon75/awp_shiny_april2018#6]
I'm working on getting the legend on the map and I'm wondering what do the last three lines on the code is trying to do.

addLegend(position="bottomright",
              pal = pal, 
              title="Legend",
              values = mapdata$est 
             **labFormat = function(type, cuts, p) {
                  n = length(cuts)
                 paste0(cuts[-n], " &ndash; ", cuts[-1])})**
   )

**Comment by jshannon75** [comment]
I'd have to really dig into it again, but I think it's a way to limit the
decimal places in the labels. Another way to do that is just round the est
column down, as there's no reason for it to be so long.

**Comment by momiji15** [comment]
I see why this was done. At a second glance, it's showing up as percentages and not the actual values. I found this post that discusses this issue: 

https://github.com/rstudio/leaflet/issues/211

**Comment by jshannon75** [comment]
Sounds good--so you got it figured out?

**Comment by momiji15** [comment]
Yup! It originally wasn't working but now I got it to work. I double checked the values with what's on the app and they are showing up correctly.
